# begin embedded pillar config
pillar:
  # use the following key to set a specific hostname
  #system_fqdn: host.domain.tld
  message_do_not_modify: "### This configuration is managed by OMS Systems Automation with SaltStack ###"
  # controls the details of installing OpenSMTPd
  smtpd:
    target: /root/src/opensmtpd-5.3-portable.tar.gz
    source: http://www.opensmtpd.org/archives/opensmtpd-5.3p1.tar.gz
    source_hash: md5=e98dfbfa17be1ff8f1e091319dfca4d8
    compile_me: /root/src/opensmtpd-5.3p1
  # some initial configuration for OMS' automation tools
  oms:
    # default values for deploy.conf
    deploy_defaults:
      hostname: localhost
      oidc_host: localhost
      vhost_base_url: http://localhost/
      oidc_base_url: http://localhost/oidc
      ssl_setup: False
    # OMS user, group, and important directories
    user: root
    group: root
    home: /var/oms
    src: /var/oms/src
    # git repos to checkout enmasse, clone to oms:src pillar key
    # the default is to include the entire OMS source code
    repos:
      oms-docs:
        url: git@github.com:IDCubed/oms-docs.git
        rev: qa-develop
      oms-deploy:
        url: git@github.com:IDCubed/oms-deploy.git
        rev: qa-develop
      oms-admin:
        url: git@github.com:IDCubed/oms-admin.git
        rev: qa-develop
      oms-kickstart:
        url: git@github.com:IDCubed/oms-kickstart.git
        rev: qa-develop
      oms-oidc:
        url: git@github.com:IDCubed/oms-oidc.git
        rev: qa-develop
      oms-core:
        url: git@github.com:IDCubed/oms-core.git
        rev: qa-develop
      oms-vrc:
        url: git@github.com:IDCubed/oms-vrc.git
        rev: qa-develop
      oms-ui:
        url: git@github.com:IDCubed/oms-ui.git
        rev: qa-develop
      oms-experimental:
        url: git@github.com:IDCubed/oms-experimental.git
        rev: qa-develop
      oms-salt-core:
        url: git@github.com:IDCubed/oms-salt-core.git
        rev: qa-develop
      oms-salt-hosting:
        url: git@github.com:IDCubed/oms-salt-hosting.git
        rev: qa-develop
      oms-inside:
        url: git@github.com:IDCubed/oms-inside.git
        rev: qa-develop
      python-oidc:
        url: git@github.com:IDCubed/python-oidc.git
        rev: qa-develop
      salt-common:
        url: git@github.com:IDCubed/salt-common.git
        rev: qa-develop
      salt-non-common:
        url: git@github.com:IDCubed/salt-non-common.git
        rev: qa-develop
      inventory:
        url: git@github.com:IDCubed/inventory.git
        rev: qa-develop
# end embedded pillar config
