# oms/base on Ubuntu 12.04 image

FROM ubuntu:12.04

MAINTAINER info@idcubed.org

ADD etc/apt/sources.list /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y -q python2.7
RUN apt-get install -y -q python-yaml
RUN apt-get install -y -q lsb-release
RUN apt-get install -y -q tmux
